<template>
  <AppShell>
    <div v-loading="loading">
      <section v-if="session" class="session-hero panel"><div><el-tag type="success">{{ session.status }}</el-tag><h2>{{ session.goal }}</h2><p>{{ session.route_match?.track_name }} · {{ session.topic }}</p></div><div class="quality"><strong>{{ session.quality_metrics?.total || 0 }}</strong><span>质量总分</span></div></section>
      <el-tabs v-if="session" v-model="active" class="tabs">
        <el-tab-pane label="Agent 轨迹" name="events"><section class="panel"><div class="event-list"><article v-for="event in session.events" :key="event.sequence" class="event clickable" @click="open(event.agent_code,event)"><span>{{ event.sequence }}</span><div><b>{{ agentName(event.agent_code) }}</b><p>{{ event.summary }}</p></div><div><el-tag type="success">{{ event.status }}</el-tag><small>{{ event.duration_ms }} ms</small></div></article></div></section></el-tab-pane>
        <el-tab-pane label="最终讲义" name="lecture"><section class="panel"><h2>{{ session.final_output?.title }}</h2><p>{{ session.final_output?.lecture?.summary }}</p><article v-if="session.final_output?.lecture?.ai_enhancement" class="ai-enhancement"><div class="tag-row"><el-tag type="success">AI 个性化补充</el-tag><el-tag type="info">{{ session.final_output.lecture.ai_enhancement.model }}</el-tag></div><p>{{ session.final_output.lecture.ai_enhancement.personalized_summary }}</p><ul><li v-for="tip in session.final_output.lecture.ai_enhancement.project_tips||[]" :key="tip">{{ tip }}</li></ul><small>引用：{{ session.final_output.lecture.ai_enhancement.citation_ids?.join('、') }} · 生成时间 {{ session.final_output.lecture.ai_enhancement.generated_at }}</small></article><article v-for="section in session.final_output?.lecture?.sections||[]" :key="section.skill_code" class="content-section clickable" @click="open(section.title,section)"><el-tag>{{ section.skill_code }}</el-tag><h3>{{ section.title }}</h3><p>{{ section.explanation }}</p><small>引用：{{ section.citation_ids?.join('、') }}</small></article></section></el-tab-pane>
        <el-tab-pane label="项目实操" name="practice"><section class="panel"><h2>{{ session.final_output?.practice?.title }}</h2><p>{{ session.final_output?.practice?.acceptance }}</p><el-steps direction="vertical" :active="1"><el-step v-for="step in session.final_output?.practice?.steps||[]" :key="step.id" :title="step.title" :description="`${step.skill_code} · ${step.proof_required}`" /></el-steps></section></el-tab-pane>
        <el-tab-pane label="仲裁与证据" name="audit"><div class="grid two"><section class="panel"><h3>仲裁结果</h3><pre>{{ JSON.stringify(session.arbitration,null,2) }}</pre></section><section class="panel"><h3>来源证据</h3><button v-for="item in session.evidence" :key="item.chunk_id" class="evidence clickable" @click="open(item.title,item)"><b>{{ item.title }}</b><span>{{ item.source_title }} · {{ item.content_version }} · {{ item.source_layer || '本地知识库' }}</span></button></section></div><section class="panel source-panel"><div class="panel-title"><div><h3>来源与生成审计</h3><p>记录实际采用的资料层、模型与降级原因，不包含 API Key</p></div></div><el-descriptions :column="2" border><el-descriptions-item label="请求策略">{{ session.source_audit?.requested_mode || session.source_mode }}</el-descriptions-item><el-descriptions-item label="实际策略">{{ session.source_audit?.effective_mode }}</el-descriptions-item><el-descriptions-item label="知识目录">{{ session.source_audit?.layers?.knowledge?.catalog_version }}</el-descriptions-item><el-descriptions-item label="联网结果">{{ session.source_audit?.layers?.web?.result_count || 0 }} 条</el-descriptions-item><el-descriptions-item v-if="session.source_audit?.layers?.ai?.model" label="生成模型">{{ session.source_audit.layers.ai.provider }} / {{ session.source_audit.layers.ai.model }}</el-descriptions-item><el-descriptions-item label="审计时间">{{ session.source_audit?.created_at }}</el-descriptions-item></el-descriptions><el-alert v-for="message in session.source_audit?.fallbacks||[]" :key="message" class="fallback" :title="message" type="warning" :closable="false" show-icon /></section></el-tab-pane>
      </el-tabs>
      <section v-if="session" class="panel feedback"><div><h3>这个学习内容适合你吗？</h3><p>反馈会立即产生可解释调整并更新画像版本。</p></div><div><el-button @click="feedback('too_hard')">太难</el-button><el-button @click="feedback('too_easy')">太简单</el-button><el-button type="success" @click="feedback('helpful')">有帮助</el-button></div></section>
    </div>
    <DetailModal v-model="detail.visible" :title="detail.title"><pre>{{ JSON.stringify(detail.data,null,2) }}</pre><a v-if="detail.data?.source_url" :href="detail.data.source_url" target="_blank" rel="noreferrer">打开原始来源 →</a></DetailModal>
  </AppShell>
</template>

<script setup lang="ts">
import { onMounted,reactive,ref } from 'vue';import { useRoute } from 'vue-router';import { ElMessage } from 'element-plus'
import AppShell from '@/components/layout/AppShell.vue';import DetailModal from '@/components/common/DetailModal.vue';import { getData,postData } from '@/api';import type { LearningSession } from '@/types/domain'
const route=useRoute(),session=ref<LearningSession|null>(null),loading=ref(true),active=ref('events'),detail=reactive({visible:false,title:'',data:null as any})
onMounted(async()=>{try{session.value=await getData(`/sessions/${route.params.id}`,{params:{include_candidates:true}})}finally{loading.value=false}})
function open(title:string,data:any){detail.title=title;detail.data=data;detail.visible=true}
async function feedback(type:string){const result=await postData<any>(`/sessions/${route.params.id}/feedback`,{feedback_type:type,content:{}});ElMessage.success(result.adjustment.message)}
function agentName(code:string){return ({lms:'学情建模 Agent',krs:'知识检索 Agent',dgs_a:'严谨生成 Agent',dgs_b:'项目生成 Agent',ars:'仲裁审核 Agent',tis:'导学交互 Agent'} as any)[code]||code}
</script>

<style scoped>
.session-hero{display:flex;justify-content:space-between;align-items:center;background:linear-gradient(120deg,#fff,#edf3ff)}.session-hero h2{margin:10px 0}.session-hero p{color:var(--muted)}.quality{text-align:center}.quality strong,.quality span{display:block}.quality strong{font-size:38px;color:#3168ee}.tabs{margin-top:18px}.event-list{display:grid;gap:10px}.event{display:grid;grid-template-columns:42px 1fr auto;gap:14px;align-items:center;padding:14px;border:1px solid var(--line);border-radius:14px;transition:.2s}.event>span{width:36px;height:36px;border-radius:12px;display:grid;place-items:center;background:#edf3ff;color:#3168ee;font-weight:700}.event p{margin:5px 0;color:var(--muted)}.event small{display:block;color:var(--muted);margin-top:5px}.ai-enhancement{padding:18px;margin:16px 0;border:1px solid #bfe8d8;border-radius:15px;background:#f1fbf7}.ai-enhancement p,.ai-enhancement li{line-height:1.75}.ai-enhancement small{color:var(--success)}.content-section{padding:17px;border-bottom:1px solid var(--line);transition:.2s}.content-section p{line-height:1.7;color:#536078}.content-section small{color:#3168ee}.evidence{width:100%;border:0;border-bottom:1px solid var(--line);padding:14px;background:transparent;text-align:left;cursor:pointer}.evidence b,.evidence span{display:block}.evidence span{color:var(--muted);margin-top:5px}.source-panel{margin-top:18px}.fallback{margin-top:10px}.feedback{margin-top:18px;display:flex;justify-content:space-between;align-items:center}.feedback h3,.feedback p{margin:4px}.feedback p{color:var(--muted)}pre{white-space:pre-wrap;word-break:break-word;background:#f7f9fd;padding:16px;border-radius:12px}@media(max-width:700px){.session-hero,.feedback{flex-direction:column;align-items:flex-start;gap:15px}}
</style>
